services:
  # app:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   networks:
  #     - network
  #   volumes:
  #     - ./:/usr/src/app
  # db:
  #   image: mariadb:10.11
  #   command: ["--max_connections=1000"]
  #   restart: unless-stopped
  #   environment:
  #     MARIADB_DATABASE: ${DB_DATABASE}
  #     MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
  #     MARIADB_PASSWORD: ${DB_PASSWORD}
  #     MARIADB_USER: ${DB_USERNAME}
  #   healthcheck:
  #     interval: 30s
  #     retries: 3
  #     test:
  #       - CMD
  #       - /usr/local/bin/healthcheck.sh
  #       - --su=mysql
  #       - --connect
  #       - --innodb_initialized
  #     timeout: 30s
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks:
  #     - network

  # nginx:
  #   image: nginx:alpine
  #   restart: unless-stopped
  #   depends_on:
  #     - app
  #   ports:
  #     - "127.0.0.1:8080:80"
  #   volumes:
  #     - ./:/usr/src/app:ro
  #     - ./nginx-app.conf:/etc/nginx/conf.d/default.conf:ro
  #   networks:
  #     - network
  #   healthcheck:
  #     interval: 30s
  #     retries: 3
  #     start_period: 20s
  #     timeout: 30s
  #     test:
  #       - CMD
  #       - curl
  #       - --fail
  #       - http://localhost/version

  # minio:
  #   image: minio/minio
  #   environment:
  #     - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
  #     - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
  #   command: server /tmp
  #   restart: unless-stopped
  #   networks:
  #     - network
  # minio-create-buckets:
  #   image: minio/mc
  #   depends_on:
  #     minio:
  #       condition: service_started
  #   entrypoint: >
  #     /bin/sh -c "
  #     /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
  #     /usr/bin/mc mb myminio/articles;
  #     exit 0;
  #     "
  #   networks:
  #     - network
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 8080:80
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./wiki:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./php.ini:/etc/php/php.ini
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
  # This key also defines the name of the database host used during setup instead of the default "localhost"
  database:
    image: mariadb
    restart: unless-stopped
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: password
    volumes:
      - ./wiki:/var/lib/mysql
volumes:
  db-data:
networks:
  network:
    name: network
